$schema: ./cache/schemas/workflow.json
projects:
- apps/*
- packages/*
- tools/*
vcs:
  hooks:
    pre-commit:
    - moon run :lint --affected
    - moon run :format --affected
  defaultBranch: main
  client: git
hasher:
  optimization: performance
pipeline:
  inheritColorsForPipedTasks: true
